base/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from base import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('catalog/', include('goods.urls', namespace='catalog')),
    path('user/', include('users.urls', namespace='user')),
    path('cart/', include('carts.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
]

if settings.DEBUG:
    urlpatterns += [
        path("__debug__/", include("debug_toolbar.urls")),
    ]
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'

urlpatterns = [
    path('create-order/', views.create_order, name='create_order' )
]

orders/models.py
from django.db import models
from decimal import Decimal
from goods.models import Bicycle

from users.models import User


class OrderItemQueryset(models.QuerySet):
    def total_price(self):
        return sum(cart.products_price() for cart in self)
    
    def total_quantity(self):
        if self:
            return sum(cart.quantity for cart in self)
        return 0


class Order(models.Model):
    user = models.ForeignKey(to=User, on_delete=models.SET_DEFAULT, blank=True, null=True, verbose_name='Користувач', default=None)
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Дата створення замовлення')
    phone = models.CharField(max_length=20, verbose_name='Телефон')
    requires_delivery = models.BooleanField(default=False, verbose_name='Потрібна доставка')
    delivery_address = models.TextField(null=True, blank=True, verbose_name='Адреса доставки')
    payment_on_get = models.BooleanField(default=False, verbose_name='Оплата при отриманні')
    is_paid = models.BooleanField(default=False, verbose_name='Оплочено')
    status = models.CharField(max_length=50, default='В обробці', verbose_name='Статус замовлення')

    class Meta:
        db_table = 'order'
        verbose_name = 'Замовлення'
        verbose_name_plural = 'Замовлення'

    def __str__(self):
        return f'Замовлення №{self.pk} | Клієнт {self.user.first_name} {self.user.last_name}'
    

class OrderItem(models.Model):
    order = models.ForeignKey(to=Order, on_delete=models.CASCADE, verbose_name='Замовлення')
    bicycle = models.ForeignKey(to=Bicycle, on_delete=models.SET_DEFAULT, null=True, verbose_name='Велосипед', default=None)
    name = models.CharField(max_length=150, verbose_name='Назва')
    price = models.DecimalField(max_digits=7, decimal_places=2, verbose_name='Ціна')
    quantity = models.PositiveIntegerField(default=0, verbose_name='Кількість')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Дата продажі')

    class Meta:
        db_table = 'order_item'
        verbose_name = 'Проданий велосипед'
        verbose_name_plural = 'Продані велосипеди'
    
    objects = OrderItemQueryset.as_manager()

    def products_price(self):
        return round(self.price * self.quantity, 2)
    
    def __str__(self):
        return f'Товар {self.name} | Замовлення {self.order.pk}'

orders/forms.py
import re
from django import forms


class CreateOrderForm(forms.Form):

    first_name = forms.CharField()
    last_name = forms.CharField()
    phone = forms.CharField()
    requires_delivery = forms.ChoiceField(choices=[
            ("0", False),
            ("1", True),
        ])
    delivery_address = forms.CharField(required=False)
    payment_on_get = forms.ChoiceField(choices=[
            ("0", False),
            ("1", True),
        ])
    
    def clean_phone(self):
        data = self.cleaned_data['phone']

        if not data.isdigit():
            raise forms.ValidationError('Номер телефону має містити лише цифри')
        
        pattern = re.compile(r'^\d{10}$')
        if not pattern.match(data):
            raise forms.ValidationError('Невірний формат номера, має бути 10 цифр')
        
        return data

    # first_name = forms.CharField(
    #     widget=forms.TextInput(
    #         attrs={
    #             'class': 'form-control',
    #             'placeholder': "Введіть ваше ім'я"
    #         }
    #     )
    # )

    # last_name = forms.CharField(
    #     widget=forms.TextInput(
    #         attrs={
    #             'class': 'form-control',
    #             'placeholder': 'Введіть ваше прізвище'
    #         }
    #     )
    # )

    # phone = forms.CharField(
    #     widget=forms.TextInput(
    #         attrs={
    #             'class': 'form-control',
    #             'placeholder': 'Номер телефону'
    #         }
    #     )
    # )

    # requires_delivery = forms.ChoiceField(
    #     widget=forms.RadioSelect(),
    #     choices=[
    #         ("0", False),
    #         ("1", True)
    #     ],
    #     initial=0,
    # )

    # delivery_address = forms.CharField(
    #     widget=forms.Textarea(
    #         attrs={
    #             'class': 'form-control',
    #             'id': 'delivery_address',
    #             'rows': 2,
    #             'placeholder': 'Введіть адресу доставки'
    #         }
    #     ),
    #     required=False,
    # )

    # payment_on_get = forms.ChoiceField(
    #     widget=forms.RadioSelect(),
    #     choices=[
    #         ("0", False),
    #         ("1", True)
    #     ],
    #     initial='card',
    # )

orders/views.py
from django.contrib import messages
from django.db import transaction
from django.forms import ValidationError
from django.shortcuts import redirect, render
from django.contrib.auth.decorators import login_required

from carts.models import Cart
from orders.models import Order, OrderItem
from .forms import CreateOrderForm


@login_required
def create_order(request):
    if request.method == 'POST':
        form = CreateOrderForm(data=request.POST)
        if form.is_valid():
            try:
                with transaction.atomic():
                    user= request.user
                    cart_items = Cart.objects.filter(user=user)

                    if cart_items.exists():
                        # Create order
                        order = Order.objects.create(
                            user=user,
                            phone=form.cleaned_data['phone'],
                            requires_delivery=form.cleaned_data['requires_delivery'],
                            delivery_address=form.cleaned_data['delivery_address'],
                            payment_on_get=form.cleaned_data['payment_on_get'],
                        )
                        # Create ordered items
                        for cart_item in cart_items:
                            bicycle = cart_item.bicycle
                            name = cart_item.bicycle.name
                            price = cart_item.bicycle.sell_price()
                            quantity = cart_item.quantity

                            if bicycle.quantity < quantity:
                                raise ValidationError(f'Недостатня кількість {name} на складі\
                                                      в наявності - {bicycle.quantity}')
                            
                            OrderItem.objects.create(
                                order=order,
                                bicycle=bicycle,
                                name=name,
                                price=price,
                                quantity=quantity,
                            )
                            bicycle.quantity -= quantity
                            bicycle.save()

                        # clear user carts after creating order
                        cart_items.delete()

                        messages.success(request, 'Замовлення оформлено')
                        return redirect('user:profile')
            except ValidationError as e:
                messages.warning(request, str(e))
                return redirect('cart:order')
            
    else:
        initial = {
            'first_name': request.user.first_name,
            'last_name': request.user.last_name,
        }

        form = CreateOrderForm(initial=initial)

    context = {
        'title': 'Оформлення замовлення',
        'form': form,
        'order': True,
    }

    return render(request, 'orders/create_order.html', context)

orders/templates/orders/create_order.html
{% extends "base.html" %}
{% load static %}
{% load carts_tags %}

{% block content %}
<div class=" bg-white p-4 mb-4 mx-2 rounded custom-shadow">
    <div class="container">
        <h3 class="text-center mb-4">Вибрані товари</h3>
        <div class="container" id="cart-items-container">
            <!-- Разметка корзины -->
            {% user_carts request as carts %}

            {% include "carts/includes/included_cart.html" %}
            <!-- Закончилась разметка корзины -->
        </div>
    </div>
    <!-- Детали заказа -->
    <div class="container">
        <h3 class="text-center">Деталі замовлення</h3>
        <div class="card mb-3">
            <div class="card-body">
                <form action="{% url 'orders:create_order' %}" method="post">
                    {% csrf_token %}
                    <div class="row">
                        <div class="col-md-6 mb-3">
                            <label for="id_first_name" class="form-label">Ім'я*:</label>
                            <input type="text" class="form-control" id="id_first_name"
                                value="{% if form.first_name.value %}{{ form.first_name.value }}{% endif %}"
                                name="first_name" required>
                                {% if form.first_name.errors %}
                                    <div class="alert alert-danger alert-dismissible fade show">{{ form.first_name.errors }}</div>
                                {% endif %}
                        </div>
                        <div class="col-md-6 mb-3">
                            <label for="id_last_name" class="form-label">Прізвище*:</label>
                            <input type="text" class="form-control" id="id_last_name" name="last_name"
                            value="{% if form.last_name.value %}{{ form.last_name.value }}{% endif %}"
                            required>
                            {% if form.last_name.errors %}
                                <div class="alert alert-danger alert-dismissible fade show">{{ form.last_name.errors }}</div>
                            {% endif %}
                        </div>
                        <div class="col-md-6 mb-3">
                            <label for="id_phone" class="form-label">Номер телефона*:</label>
                            <input type="text" class="form-control" id="id_phone" name="phone"
                                value="{% if form.phone.value %}{{ form.phone.value }}{% endif %}"
                                placeholder="В форматі: XXX-XXX-XX-XX"
                                required>
                                {% if form.phone.errors %}
                                    <div class="alert alert-danger alert-dismissible fade show">{{ form.phone.errors }}</div>
                                {% endif %}
                        </div>
                        <div class="col-md-12 mb-3">
                            <label for="delivery" class="form-label">Спосіб доставки: </label>
                            <div class="form-check form-check-inline">
                                <input class="form-check-input" type="radio" name="requires_delivery"
                                    id="id_requires_delivery" value="1" checked>
                                <label class="form-check-label" for="id_requires_delivery">Потрібна
                                    доставка</label>
                            </div>
                            <div class="form-check form-check-inline">
                                <input class="form-check-input" type="radio" name="requires_delivery"
                                    id="id_requires_delivery" value="0">
                                <label class="form-check-label" for="id_requires_delivery">Самовивіз</label>
                            </div>
                            {% if form.requires_delivery.errors %}
                                <div class="alert alert-danger alert-dismissible fade show">{{ form.requires_delivery.errors }}</div>
                            {% endif %}
                        </div>
                        <div class="mb-3" id="deliveryAddressField">
                            <label for="id_delivery_address" class="form-label">Адреса
                                доставки*:</label>
                            <textarea class="form-control" id="id_delivery_address"
                                value="{% if form.delivery_address.value %}{{ form.delivery_address.value }}{% endif %}"
                                name="delivery_address" rows="2"></textarea>
                                {% if form.delivery_address.errors %}
                                    <div class="alert alert-danger alert-dismissible fade show">{{ form.delivery_address.errors }}</div>
                                {% endif %}
                        </div>
                        <div class="col-md-12 mb-3">
                            <label class="form-label">Спосіб оплати: </label>
                            <div class="form-check form-check-inline">
                                <input class="form-check-input" type="radio" name="payment_on_get"
                                    id="id_payment_on_get" value="0" checked>
                                <label class="form-check-label" for="id_payment_on_get">Оплата
                                    картою</label>
                            </div>
                            <div class="form-check form-check-inline">
                                <input class="form-check-input" type="radio" name="payment_on_get"
                                    id="id_payment_on_get" value="1">
                                <label class="form-check-label" for="id_payment_on_get">Готівкою/картою
                                    при отриманні</label>
                            </div>
                            {% if form.payment_on_get.errors %}
                                <div class="alert alert-danger alert-dismissible fade show">{{ form.payment_on_get.errors }}</div>
                            {% endif %}
                        </div>
                    </div>
                    <button type="submit" class="btn btn-dark">Оформити замовлення</button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}