base/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from base import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('catalog/', include('goods.urls', namespace='catalog')),
    path('user/', include('users.urls', namespace='user')),
    path('cart/', include('carts.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
]

if settings.DEBUG:
    urlpatterns += [
        path("__debug__/", include("debug_toolbar.urls")),
    ]
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

goods/urls.py
from django.urls import path
from goods import views

app_name = 'catalog'

urlpatterns = [
    path('search/', views.catalog, name='search'),
    path('<slug:category_slug>/', views.catalog, name='index'),
    path('product/<slug:product_slug>/', views.product, name='product'),
]

users/urls.py
from django.urls import path
from users import views

app_name = 'users'

urlpatterns = [
    path('login/', views.login, name='login'),
    path('registration/', views.registration, name='registration'),
    path('profile/', views.profile, name='profile'),
    path('users-cart/', views.users_cart, name='users_cart'),
    path('logout/', views.logout, name='logout'),
    # for password reset
    path('forgotPassword/', views.forgotPassword, name="forgotPassword"),
    path('resetpassword_validate/<uidb64>/<token>/', views.resetpassword_validate, name='resetpassword_validate'),
    path('resetPassword/', views.resetPassword, name="resetPassword"),
]

orders/models.py
from django.db import models
from decimal import Decimal
from goods.models import Bicycle

from users.models import User


class OrderItemQueryset(models.QuerySet):
    def total_price(self):
        return sum(cart.products_price() for cart in self)
    
    def total_quantity(self):
        if self:
            return sum(cart.quantity for cart in self)
        return 0


class Order(models.Model):
    user = models.ForeignKey(to=User, on_delete=models.SET_DEFAULT, blank=True, null=True, verbose_name='Користувач', default=None)
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Дата створення замовлення')
    phone = models.CharField(max_length=20, verbose_name='Телефон')
    requires_delivery = models.BooleanField(default=False, verbose_name='Потрібна доставка')
    delivery_address = models.TextField(null=True, blank=True, verbose_name='Адреса доставки')
    payment_on_get = models.BooleanField(default=False, verbose_name='Оплата при отриманні')
    is_paid = models.BooleanField(default=False, verbose_name='Оплочено')
    status = models.CharField(max_length=50, default='В обробці', verbose_name='Статус замовлення')

    class Meta:
        db_table = 'order'
        verbose_name = 'Замовлення'
        verbose_name_plural = 'Замовлення'

    def __str__(self):
        return f'Замовлення №{self.pk} | Клієнт {self.user.first_name} {self.user.last_name}'
    

class OrderItem(models.Model):
    order = models.ForeignKey(to=Order, on_delete=models.CASCADE, verbose_name='Замовлення')
    bicycle = models.ForeignKey(to=Bicycle, on_delete=models.SET_DEFAULT, null=True, verbose_name='Велосипед', default=None)
    name = models.CharField(max_length=150, verbose_name='Назва')
    price = models.DecimalField(max_digits=7, decimal_places=2, verbose_name='Ціна')
    quantity = models.PositiveIntegerField(default=0, verbose_name='Кількість')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Дата продажі')

    class Meta:
        db_table = 'order_item'
        verbose_name = 'Проданий велосипед'
        verbose_name_plural = 'Продані велосипеди'
    
    objects = OrderItemQueryset.as_manager()

    def products_price(self):
        return round(self.price * self.quantity, 2)
    
    def __str__(self):
        return f'Товар {self.name} | Замовлення {self.order.pk}'

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser, BaseUserManager



class MyAccountManager(BaseUserManager):
    def create_user(self, first_name, last_name, username, email, password=None):
        if not email:
            raise ValueError('Юзер повинен мати e-mail')
        
        if not username:
            raise ValueError('Юзер повинен мати username')
        
        user = self.model(
            email = self.normalize_email(email),
            username = username,
            first_name = first_name,
            last_name = last_name,
        )

        user.set_password(password)
        user.save(using=self._db)
        return user
    
    def create_superuser(self, first_name, last_name, username, email, password):
        user = self.create_user(
            email = self.normalize_email(email),
            username = username,
            password = password,
            first_name = first_name,
            last_name = last_name,
        )

        user.is_active = True
        user.is_admin = True
        user.is_staff = True
        user.is_superadmin = True

        user.save(using=self._db)
        return user


class User(AbstractUser):
    email = models.EmailField(unique=True)
    image = models.ImageField(upload_to='users_images', blank=True, null=True, verbose_name='Аватар')
    phone_number = models.CharField(max_length=10, blank=True, null=True)

    objects = MyAccountManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    class Meta:
        db_table = 'user'
        verbose_name = 'Користувача'
        verbose_name_plural = 'Користувачі'

    def __str__(self):
        return self.username

users/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, UserChangeForm
from users.models import User


class UserLoginForm(AuthenticationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields.pop('username')
    class Meta:
        model = User
        fields = ['email', 'password']

    email = forms.CharField()
    password = forms.CharField()

    # username = forms.CharField(label="Ім'я користувача", widget=forms.TextInput(attrs={"autofocus": True,
    #                                                          'class': 'form-control',
    #                                                          'placeholder': "Введіть ім'я користувача"}))
    # password = forms.CharField(label="Пароль",
    #     widget=forms.PasswordInput(attrs={"autocomplete": "current-password",
    #                                       'class': 'form-control',
    #                                       'placeholder': 'Введіть пароль'}),
    # )


class UserRegistrationForm(UserCreationForm):
    class Meta:
        model = User
        fields = (
            'first_name', 
            'last_name', 
            'username', 
            'email', 
            'password1', 
            'password2')
        
    first_name = forms.CharField()
    last_name = forms.CharField()
    username = forms.CharField()
    email = forms.CharField()
    password1 = forms.CharField()
    password2 = forms.CharField()
    

    # first_name = forms.CharField(
    #     widget=forms.TextInput(
    #         attrs={
    #             'class': 'form-control', 
    #             'placeholder': "Введіть ваше ім'я"}))
    # last_name = forms.CharField(
    #     widget=forms.TextInput(
    #         attrs={
    #             'class': 'form-control', 
    #             'placeholder': 'Введіть ваше прізвище'}))
    # username = forms.CharField(
    #     widget=forms.TextInput(
    #         attres={
    #             'class': 'form-control', 
    #             'placeholder': 'Введіть ваш нікнейм'}))
    # email = forms.EmailField(
    #     widget=forms.EmailInput(
    #         attrs={
    #             'class': 'form-control', 
    #             'placeholder': 'Введіть ваш email *youremail@example.com'}))
    # password1 = forms.CharField(
    #     widget=forms.PasswordInput(
    #         attrs={
    #             'class': 'form-control', 
    #             'placeholder': 'Введіть ваш пароль'}))
    # password2 = forms.CharField(
    #     widget=forms.PasswordInput(
    #         attrs={
    #             'class': 'form-control', 
    #             'placeholder': 'Підтвердіть ваш пароль'}))


class ProfileForm(UserChangeForm):
    class Meta:
        model = User
        fields = (
            'image',
            'first_name',
            'last_name',
            'username',
            'email',
        )
    image = forms.ImageField(required=False)
    first_name = forms.CharField()
    last_name = forms.CharField()
    username = forms.CharField()
    email = forms.CharField()
    
    # image = forms.ImageField(widget=forms.FileInput(attrs={'form-control mt-3'}),required=False)
    # first_name = forms.CharField(
    #     widget=forms.TextInput(
    #         attrs={
    #             'class': 'form-control', 
    #             'placeholder': "Введіть ім'я"}))
    # last_name = forms.CharField(
    #     widget=forms.TextInput(
    #         attrs={
    #             'class': 'form-control', 
    #             'placeholder': 'Введіть прізвище'}))
    # username = forms.CharField(
    #     widget=forms.TextInput(
    #         attres={
    #             'class': 'form-control', 
    #             'placeholder': 'Введіть нікнейм'}))
    # email = forms.EmailField(
    #     widget=forms.EmailInput(
    #         attrs={
    #             'class': 'form-control', 
    #             'placeholder': 'Введіть ваш email *youremail@example.com'}))

users/views.py
from django.db.models import Prefetch
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib import auth, messages
from django.contrib.auth import get_user_model

# Verification email
from django.contrib.sites.shortcuts import get_current_site
from django.template.loader import render_to_string, get_template
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.utils.encoding import force_bytes
from django.contrib.auth.tokens import default_token_generator
from django.core.mail import EmailMessage

from orders.models import Order, OrderItem
from .forms import UserLoginForm, UserRegistrationForm, ProfileForm
from carts.models import Cart


User = get_user_model()

def authenticate_user(email=None, password=None):
    try:
        user = User.objects.get(email=email)
        if user.check_password(password):
            return user
    except User.DoesNotExist:
        return None


def login(request):
    if request.method == 'POST':
        print('post')
        form = UserLoginForm(data=request.POST)
        print(form.errors)
        if form.is_valid():
            print('post_valid')
            email = request.POST['email']
            password = request.POST['password']
            print('authenticate')
            user = authenticate_user(email=email, password=password)

            session_key = request.session.session_key
            
            if user:
                auth.login(request, user)
                messages.success(request, 'Ви успішно увійшли в акаунт')

                if session_key:
                    Cart.objects.filter(session_key=session_key).update(user=user)

                redirect_page = request.POST.get('next', None)
                if redirect_page and redirect_page != reverse('user:logout'):
                    return HttpResponseRedirect(request.POST.get('next'))
                
                return HttpResponseRedirect(reverse('main:index'))
    else:
        print('get')
        form = UserLoginForm()
        
    context = {
        'title': 'VELOS - Авторизація',
        'form': form,
    }
    return render(request, 'users/login.html', context)


def registration(request):
    if request.method == 'POST':
        form = UserRegistrationForm(data=request.POST)
        if form.is_valid():
            form.save()

            session_key = request.session.session_key

            user = form.instance
            auth.login(request, user)

            if session_key:
                Cart.objects.filter(session_key=session_key).update(user=user)

            messages.success(request, f'{user.username}, Ви успішно зареєстровані та увійшли в акаунт')
            return HttpResponseRedirect(reverse('main:index'))
    else:
        form = UserRegistrationForm()

    context = {
        'title': 'VELOS - Регістрація',
        'form': form,
    }
    return render(request, 'users/registration.html', context)


@login_required
def profile(request):
    if request.method == 'POST':
        form = ProfileForm(data=request.POST, instance=request.user, files=request.FILES)
        if form.is_valid():
            form.save()
            messages.success(request, 'Профайл успішно обновлений')
            return HttpResponseRedirect(reverse('user:profile'))
    else:
        form = ProfileForm(instance=request.user)

    orders = (
        Order.objects.filter(user=request.user).prefetch_related(
        Prefetch(
            'orderitem_set',
            queryset=OrderItem.objects.select_related('bicycle'),
        )
    ).order_by('id')
    )

    context = {
        'title': 'VELOS - Кабінет',
        'form': form,
        'orders': orders,
    }
    return render(request, 'users/profile.html', context)


def users_cart(request):
    return render(request, 'users/users_cart.html')


@login_required
def logout(request):
    messages.success(request, f'{request.user.username}, Ви вийшли')
    auth.logout(request)
    return redirect('main:index')


def forgotPassword(request):
    if request.method == 'POST':
        email = request.POST['email']
        if User.objects.filter(email=email).exists():
            user = User.objects.get(email__iexact=email)

            # Reset password email
            current_site = get_current_site(request)
            mail_subject = "Змініть свій пароль"
            message = render_to_string('users/reset_password_email.html', {
                'user': user,
                'domain': current_site,
                'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                'token': default_token_generator.make_token(user),
            })
            to_email = email
            send_email = EmailMessage(mail_subject, message, to=[to_email])
            send_email.send() 

            messages.success(request, 'Посилання для зміни пароля було надіслане на ваш email') 
            return redirect('user:login')        

        else:
            messages.error(request, 'Такого Акаунту не існує')
            return redirect("user:forgotPassword")
        
    return render(request, 'users/forgotPassword.html')


def resetpassword_validate(request, uidb64, token):
    try:
        uid = urlsafe_base64_decode(uidb64).decode()
        user = User._default_manager.get(pk=uid)
    except(TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None

    if user is not None and default_token_generator.check_token(user, token):
        request.session['uid'] = uid
        messages.success(request, "Будь-ласка, змініть свій пароль")
        return redirect("user:resetPassword")
    else:
        messages.error(request, "This link has been expired!")
        return redirect("user:login")
    

def resetPassword(request):
    if request.method == 'POST':
        password = request.POST['password']
        confirm_password = request.POST['confirm_password']

        if password == confirm_password:
            uid = request.session.get('uid')
            user = User.objects.get(pk=uid)
            user.set_password(password)
            user.save()
            messages.success(request, "Пароль змінено успішно!")
            return redirect("user:login")

        else:
            messages.error(request, "Паролі не співпадають!")
            return redirect("resetPassword")
    else:
        return render(request, 'users/resetPassword.html')

users/templates/users/forgotPassword.html
{% extends 'base.html' %}

{% block content %}

<!-- ========================= SECTION CONTENT ========================= -->
<section class="section-content padding-y" style="min-height:84vh">


  <!-- ============================ COMPONENT LOGIN   ================================= -->
    <div class="mx-auto" style="max-width: 600px; margin-top:100px;">
      
        <div>
        <h4 class="mb-4">Забули пароль</h4>
        {% include 'includes/notifications.html' %}
        <form action="{% url 'user:forgotPassword' %}" method="POST">
          {% csrf_token %}
            <div>
         <input type="email" class="form-control" placeholder="Email Address" name="email" >
            </div> <!-- form-group// -->
            
            
            <div class="mt-2 mb-2">
                Згадали пароль?
              <a href="{% url 'user:login' %}" class="float-right">Увійти.</a> 
             
            </div> 
            <div>
                <button type="submit" class="btn btn-dark btn-block"> Надіслати  </button>
            </div>   
        </form>
        </div> 
      </div> 

  
       <p class="text-center mt-4">Ще не маєте акаунт? <a href="{% url 'user:registration' %}">Зареєструватися</a></p>
       <br><br>
  <!-- ============================ COMPONENT LOGIN  END.// ================================= -->
  
  
  </section>
  <!-- ========================= SECTION CONTENT END// ========================= -->














{% endblock %}

users/templates/users/profile.html
{% extends "base.html" %}
{% load static %}
{% load carts_tags %}


{% block content %}
<div class="row">
    <div class="container mt-5">
        <div class="row">
            <!-- Профиль с данными пользователя -->
            <div class="col-md-5">
                <div class=" bg-white p-4 mb-4 mx-2 rounded custom-shadow">
                    <h3 class="text-center mb-4">Профіль юзера</h3>
                    <form action="{% url "users:profile" %}" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="row">
                            <div class="col-md-12 mb-3 text-center">
                                {% if user.image %}
                                <img src="{{ user.image.url }}"
                                    alt="Аватар пользователя" class="img-fluid rounded-circle"
                                    style="max-width: 150px;">
                                {% else %}
                                <img src="{% static "deps/images/baseavatar.jpg" %}"
                                    alt="Аватар пользователя" class="img-fluid rounded-circle"
                                    style="max-width: 150px;">
                                {% endif %}
                                <input type="file" class="form-control mt-3" id="id_image"
                                    name="image"
                                    accept="image/*">
                                    {% if form.image.errors %}
                                        <div class="alert alert-danger alert-dismissible fade show">{{ form.image.errors }}</div>
                                    {% endif %}
                            </div>
                            <div class="col-md-12 mb-3">
                                <label for="id_first_name" class="form-label">Ім'я*</label>
                                <input type="text" class="form-control" id="id_first_name"
                                    name="first_name"
                                    placeholder="Введіть ваше ім'я" 
                                    value="{{ form.first_name.value }}" 
                                    required>
                                    {% if form.first_name.errors %}
                                        <div class="alert alert-danger alert-dismissible fade show">{{ form.first_name.errors }}</div>
                                    {% endif %}
                            </div>
                            <div class="col-md-12 mb-3">
                                <label for="id_last_name" class="form-label">Прізвище*</label>
                                <input type="text" class="form-control" id="id_last_name"
                                    name="last_name"
                                    placeholder="Введіть прізвище" 
                                    value="{{ form.last_name.value }}" 
                                    required>
                                    {% if form.last_name.errors %}
                                        <div class="alert alert-danger alert-dismissible fade show">{{ form.last_name.errors }}</div>
                                    {% endif %}
                            </div>
                            <div class="col-md-12 mb-3">
                                <label for="id_username" class="form-label">Ім'я користувача*</label>
                                <input type="text" class="form-control" id="id_username"
                                    name="username"
                                    placeholder="Введіть нікнейм" 
                                    value="{{ form.username.value }}" 
                                    required>
                                    {% if form.username.errors %}
                                        <div class="alert alert-danger alert-dismissible fade show">{{ form.username.errors }}</div>
                                    {% endif %}
                            </div>
                            <div class="col-md-12 mb-3">
                                <label for="id_email" class="form-label">Email*</label>
                                <input type="email" class="form-control" id="id_email"
                                    name="email"
                                    placeholder="Введіть ваш email *youremail@example.com" 
                                    value="{{ form.email.value }}"
                                    required>
                                    {% if form.email.errors %}
                                        <div class="alert alert-danger alert-dismissible fade show">{{ form.email.errors }}</div>
                                    {% endif %}
                            </div>
                        </div>
                        <button type="submit" class="btn btn-dark">Зберегти</button>
                    </form>
                </div>
            </div>
            <!-- Корзина -->
            {% user_carts request as carts %}
            <div class="col-md-7">
                <div class=" bg-white p-4 mb-4 mx-2 rounded custom-shadow">
                    <h3 class="text-center mb-4">Корзина</h3>
                    <div class="container" id="cart-items-container">
                        <!-- Разметка корзины -->
                        {% include "carts/includes/included_cart.html" %}
                        <!-- Закончилась разметка корзины -->
                    </div>
                    {% comment %} {% if carts %}
                        <a class="btn btn-dark" href="../orders/create_order.html">
                            Оформить заказ
                        </a>
                    {% endif %} {% endcomment %}
                </div>
            </div>
            <!-- Оформленные заказы -->
            <div class="col-md-12">
                <div class=" bg-white p-4 mb-4 mx-2 rounded custom-shadow">
                    <h3 class="text-center mb-4">Мої Замовлення</h3>
                     <!-- Разметка заказов -->
                     <div class="container">
                        <div class="accordion" id="accordionExample">
                            {% for order in orders %}
                            <div class="accordion-item">
                                <h2 class="accordion-header" id="heading{{ order.id }}">
                                    <button class="accordion-button {% if order != orders.0 %}collapsed{% endif %}" type="button" data-bs-toggle="collapse" data-bs-target="#collapse{{ order.id }}" aria-expanded="false" aria-controls="collapse{{ order.id }}">
                                        Замовлення № {{ order.id }} - {{ order.created_at }} | Статус: <strong class="mx-2">{{order.status}}</strong>
                                    </button>
                                </h2>
                                <div id="collapse{{ order.id }}" class="accordion-collapse collapse {% if order == orders.0 %}show{% endif %}" aria-labelledby="heading{{ order.id }}" data-bs-parent="#accordionExample">
                                    <div class="accordion-body">
                                        <table class="table table-dark table-hover">
                                            <thead>
                                                <tr>
                                                    <th>Товар</th>
                                                    <th>Кількість</th>
                                                    <th>Ціна</th>
                                                    <th>Загальна вартість</th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                                {% for item in order.orderitem_set.all %}
                                                <tr>
                                                    <td><a class="text-white" href="{% url 'catalog:product' item.bicycle.slug %}">{{ item.bicycle.name }}</a></td>
                                                    <td>{{ item.quantity }}</td>
                                                    <td>{{ item.price }}</td>
                                                    <td>{{ item.products_price }}</td>
                                                    
                                                </tr>
                                                {% endfor %}
                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                            </div>
                            {% endfor %}
                        </div>
                    </div>
                    {% comment %} <div class="container">
                        <div class="accordion" id="accordionExample">
                            <div class="accordion-item">
                                <h2 class="accordion-header" id="heading1">
                                    <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapse1" aria-expanded="false" aria-controls="collapse1">
                                        Заказ № 256 - 09 сентября 2023 9:04 | Статус:<strong class="mx-2"> В обработке</strong>
                                    </button>
                                </h2>
                                <div id="collapse1" class="accordion-collapse collapse show" aria-labelledby="heading1" data-bs-parent="#accordionExample">
                                    <div class="accordion-body">
                                        <table class="table table-dark table-hover">
                                            <thead>
                                                <tr>
                                                    <th>Товар</th>
                                                    <th>Количество</th>
                                                    <th>Цена</th>
                                                    <th>Общая стоимость</th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                                <tr>
                                                    <td><a class="text-white" href="#">Комплект стол и три стула</a></td>
                                                    <td>1</td>
                                                    <td>255.00 $</td>
                                                    <td>255.00 $</td>
                                                    
                                                </tr>
                                            </tbody>
                                        </table>
                                        <div class="d-flex justify-content-between">
                                            <p><strong>Итого:</strong></p>
                                            <p><strong>255.00 $</strong></p>

                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="accordion-item">
                                <h2 class="accordion-header" id="heading2">
                                    <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapse2" aria-expanded="false" aria-controls="collapse2">
                                        Заказ № 248 - 01 августа 2023 11:28 | Статус: <strong>Получен</strong>
                                    </button>
                                </h2>
                                <div id="collapse2" class="accordion-collapse collapse" aria-labelledby="heading2" data-bs-parent="#accordionExample">
                                    <div class="accordion-body">
                                        <table class="table table-dark table-hover">
                                            <thead>
                                                <tr>
                                                    <th>Товар</th>
                                                    <th>Количество</th>
                                                    <th>Цена</th>
                                                    <th>Общая стоимость</th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                                <tr>
                                                    <td><a class="text-white" href="#">Стул офисный</a></td>
                                                    <td>2</td>
                                                    <td>30.00 $</td>
                                                    <td>60.00 $</td>
                                                    
                                                </tr>
                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div> {% endcomment %}
                    <!-- Закончилась разметка заказов -->
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

users/templates/users/reset_password_email.html
{% autoescape off %}

Доброго здоров'я, {{ user.first_name }}!

За вашим запитом, для зміни пароля натисніть на це посилання...
http://{{domain}}{% url 'user:resetpassword_validate' uidb64=uid token=token %}

Якщо думаєте, що це не ви, ігноруйте це повідомлення...


{% endautoescape %}